language: go

go:
- "1.12.x"

env:
- GO111MODULE=on

before_install:
- make setup-lint

script:
- make lint
- make test
- make build

deploy:
  provider: releases
  file:
  - cis
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: xjcMGVwMHqEtt3D0pyuXRjn9WwXKe6BmPFlLXn2xvqr/CyjRqDwuSCWhYTfHnWuaQ1RzGJF0PeQJjXopA20sdua3APNFGRpf2FUFP2Um461mw5NXrjsU/Y5cORLF9zHyPy+/tdBDk//N8c3dyOixO0fNfSSBsyZgZD31nENr2sBGMA1ZDPOk6/Ai+kUXg9KvfZ6NH6gHLnSpsbnvyZ9OCRvFmZLtkBsLvNYQm2czkICfGZ9VRb7h4IuobX4RuoZ8KE9YxUuFOoenuSTGa6kiqnYBkIEbecoi9HCRBQorbXlD0GMu5m4ULDytsQws72on3tmByIh6I37VqSn6gcYASe3wNHUdEC3TFSBgQZX/qm1jl2OWzjDbfCf6HPFd/l7/C04jUkIqG8HZmDk2i+lAlSaoZExzor1MXMPYiEyLNXta3LSSqa+aj/9gKG+0scjhx+mPRCdtB9Fh04oBmukTP98xwzycxZgDW9o2hV0UcVRTmgll+D2sKqalSM1MGGtuJFJzJyuCrXlK6Ajs6F6YSIr3xVPyhyL9M75b4hOG+YKylr0zQ97/pexYekpXft7bjE1wa7ndqY/zsCulVeZB0Xm3KtLj5Er41ZFUbyLaexk8p1he8MHtQ3jGFBKPlLQguXZMHIEYsnhjrvh0tq475fXYlZGumMK6JW4EGTqAZgM=
